### ISSUE TITLE
Location of zip file

### ISSUE THREAD

**Issue by richarth** [Jumoo/uSync.Migrations.Packers#3]
Hi,

I was wondering where the zip file is saved as I can't find it after the make pack process has finished.

On the file system I have a uSync folder which has a data folder containing all configs.  The uSync folder also contains a MigrationPacks folder.  Whilst the make pack process runs, I can see a folder is created within the MigrationPacks folder and data is output there.  Once the process finishes everything in the MigrationPacks folder is gone.  I'm assuming that's where the zip file should be.

I've checked the Umbraco log file and the last entry mentions exporting the domain settings, there are no further entries after that.

I'm running this on an Umbraco 7.15.11 with 7.0.1 of this package.

Thanks

Richard

**Comment by ProNotion** [comment]
@richarth  You should be presented with a dialog giving you the option to save it somewhere.

However, I kept accidentally closing it without saving so I submitted a [pull request](https://github.com/Jumoo/uSync.Migrations.Packers/pull/2) that also saved it to the `usync/MigrationPacks` folder but not sure if that has been released yet.

**Comment by richarth** [comment]
Thanks @ProNotion.

I don't remember it presenting me with a dialog, but I did discover later on that I had a lot of empty zip files end up in my downloads folder.

To answer my own question the zip files are created in the MigrationPacks folder.  It wasn't working with the packer I downloaded but when I grabbed this repo and used a copy built from the source it started working 🤷.
