### ISSUE TITLE
Updated package not working

### ISSUE THREAD

**Issue by craigs100** [Jumoo/uSync.Migrations.Packers#5]
With (uSync.BackOffice 4.0.15.0) (uSync.Core 6.0.15.0) [uSync.Content: 4.1.9.1] [Migration.Packer: 1.0.0]

This new version (7.1.0) doesn't work on the V7.15.10 site at all. As soon as I navigate to the Developer section I get the error:-

Request error: The URL returned a 404 (not found): /app_plugins/uSync.Content/uSyncDashboardContent.html

Then in the uSync BackOffice tab the Content and Migrations tabs are totally empty and there is no Migrations folder in the uSync folder. I have restarted the site several times and performed several full exports.

Please advise.

**Comment by KevinJump** [comment]
Hi, 

did you also have uSync and uSync.ContentEdtion installed? 

![image](https://github.com/Jumoo/uSync.Migrations.Packers/assets/431231/44f8b48a-8fe1-45b5-a5e7-1f93a3b7c63f)


I just tried a few combinations to try and break it, but it is working here.

**Comment by craigs100** [comment]
I didn't have uSync.ContentEdition in, but I have now. I've restarted, re-exported and still don't get a migrations folder and/or .zip file created anywhere. I'm running on a local Win10 VM so permissions shouldn't be an issue. I can see the V9 sub folders rebuilding on an export, but that's all that happens :(

![image](https://github.com/Jumoo/uSync.Migrations.Packers/assets/1143883/935bbb9b-8567-413b-b5ca-e12bd823830c)

The Migrations tab is totally blank too.
